### ISSUE TITLE
Audio recorder is saving the same file for different records

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-gb#242] opened 2015-07-16 14:41 UTC
I used FieldtripGB default audio recorder. I captured one audio record and an audio45.m4a was saved inside assets/audio/ folder of the app. I captured a second audio record and a new file with the same filename was created on the same folder as before. I synced with dropbox and ended up with the same audio file within the 2 different records.

**Comment by gmh04** [comment] 2015-07-17 08:43
Plugin is doing the right thing by using an index in the file name:

https://github.com/edina/spatial-memories-cordova-plugin-media-capture/blob/edina-0.3.2.1/src/android/AudioRecorderActivity.java#L102-L111

The problem is ftopen moves the file: https://github.com/edina/fieldtrip-open/blob/ftgb-1.5/src/www/js/records.js#L1216 so next time the plugin reads for audio files from Environment.getExternalStorageDirectory() it uses the same index as last time.

I would be tempted to copy the file instead of moving it.

**Comment by gmh04** [comment] 2015-07-17 10:28
https://github.com/edina/fieldtrip-open/commit/438b772e7c55e2404d47e592a95602ef191c43ed

**Comment by gmh04** [comment] 2015-07-17 10:42
fix available in http://fieldtripgb.edina.ac.uk/releases/1.5.1.0/MainActivity-debug.apk

**Closed by gmh04** 2015-07-17 10:42 UTC
Labels: android, bug
